# -*- coding: utf-8 -*-
"""ml_workshop day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K97MZjy9R0i81dkOnq5_ydpOWlUaJif0
"""

#DAY 1:
#EDA : Exploratory data analysis
""" Understanding and working with data """


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=sns.load_dataset("iris")
print(df.head())

print(df.head(10))

print(df.tail())

print("shape:",df.shape)

print("columns:",df.columns.tolist())

df.info()

print(df.isnull().sum())

print("Total Misssing Value:",df.isnull().sum().sum())

print("number of rows and columns are",len(df))

print("number of columns",df.shape[1])

print("number of rows",len(df))

print(df["species"].value_counts())

print(df["species"].value_counts(normalize=True)*100,"")

print(df["species"].unique())

print("number of unique species",df["species"].nunique())

df.describe()

print(df.select_dtypes)

sns.countplot(data=df,x="species")
plt.title("Number of flowers by species")
plt.xlabel("Species")
plt.ylabel("Count")
plt.show()

sns.histplot(data=df, x="sepal_length", bins=10, kde=True)

sns.boxplot(data=df, x="species", y="petal_length")
plt.title("Box Plot of Petal Length by Species")
plt.xlabel("Species")
plt.ylabel("Petal Length")
plt.show()

print(df.describe)

df.hist(figsize=(12,10))
plt.suptitle("Feature Distributions")
plt.show()

# 3. EDA
# ===============================
# Histogram
df.hist(figsize=(12,10))
plt.suptitle("Feature Distributions")
plt.show()

