# -*- coding: utf-8 -*-
"""ml_wshop_day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GaY4yz31Zaad227Cml4g7BGGDfeTxVEy
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

import statsmodels.formula.api as smf

# Force pandas to display all columns without wrapping
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

# Optional: Round floats to 2 decimal places for cleaner viewing
pd.set_option('display.float_format', lambda x: '%.2f' % x)


#loading the data
url="https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv"
df=pd.read_csv(url)

x_slr=df[['rm']]
y=df['medv']


x_train, x_test, y_train, y_test = train_test_split(x_slr, y, test_size=0.3, random_state=565)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

#simple linear reg
slr=LinearRegression()
slr.fit(x_train, y_train)
y_pred=slr.predict(x_test)
y_pred

"""To know if the predictions are 'right', we evaluate the model's performance using various regression metrics. Here are some common ones:"""

# Calculate evaluation metrics
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse) # Root Mean Squared Error
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
print(f"R-squared (R2) Score: {r2:.2f}")
print(f"Mean Absolute Error (MAE): {mae:.2f}")

"""### Explanation of Metrics:

*   **Mean Squared Error (MSE)**: This is the average of the squared differences between the actual and predicted values. It gives higher weight to larger errors, making it sensitive to outliers. A lower MSE indicates a better fit.

*   **Root Mean Squared Error (RMSE)**: This is the square root of the MSE. It's often preferred over MSE because it has the same units as the target variable, making it easier to interpret. A lower RMSE is better.

*   **R-squared (R2) Score**: This metric represents the proportion of the variance in the dependent variable that is predictable from the independent variable(s). It ranges from 0 to 1, where 1 indicates that the model explains all the variability of the response data around its mean. A higher R2 score indicates a better fit.

*   **Mean Absolute Error (MAE)**: This is the average of the absolute differences between the actual and predicted values. It's less sensitive to outliers than MSE or RMSE, as it doesn't square the errors. A lower MAE indicates a better fit.
"""

#Linear regression visualizer
plt.scatter(x_test,y_test,label="actual")
plt.plot(x_test,y_pred,color="red",label="predicted line")
plt.title("SLR Fit: RM VS MEDV")
plt.legend()
plt.show()

#multiple linear reg
x_mlr=df[['rm','lstat','ptratio','crim','tax']]
y=df['medv']
x_train, x_test, y_train, y_test = train_test_split(x_mlr, y, test_size=0.3, random_state=565)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

mlr=LinearRegression()
mlr.fit(x_train,y_train)
y_pred_mlr=mlr.predict(x_test)
y_pred_mlr

print("MLR result")
print("R2",r2_score(y_test,y_pred_mlr))

#coefficients
coeff_df=pd.DataFrame({"Feature":x_mlr.columns,"Coefficients":mlr.coef_})
print(coeff_df)

#PREDICTIOM TABLE

pred_df=pd.DataFrame({"Actaul":y_test.values,"Predicted":y_pred_mlr})
print(pred_df.head())

3#OLD MODEL(Statistical View)

ols_model=smf.ols(formula="medv ~ rm + lstat + ptratio+crim+tax",data=df)
ols_result=ols_model.fit()
print(ols_result.summary())